# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install-dotnet    
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
     
    - name: InstallDatabase
      uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: 'mariadb'
        mysql-version: '10.6'
        root-password: 'root'
        user: 'user'
        password: 'password'
    - run: mysql -uroot -proot -h127.0.0.1 -e 'SELECT version()'

   
    - name: build
      run: dotnet build
    
    - name: release
      run: dotnet publish -o ./release
      
    - name: test
      run: dotnet test
      
    - name: build container
      run: docker build . --file Dockerfile --tag dwo1327
      #working-directory: ./release
    
    - name: tag
      run: docker tag dwo1327 idi2019.azurecr.io/dwo1327-gb-b
      
    - name: mysqlDocker
      run: docker run -d --name mysql mysql
    
    - name: run_docker
      run: docker run --rm --name stat -it -d -p 8090:8080 -e ConnectionStrings:dbconnection="Server=mysql;Database=guestbook;User Id=root;Password=root;" dwo1327
      
    - name: loginAZ
      uses: azure/docker-login@v1
      with: 
       login-server: idi2019.azurecr.io
       username: ${{ secrets.REG_USERNAME }}
       password: ${{ secrets.REG_PASSWORD }}
           
    - name: publish
      run: docker push idi2019.azurecr.io/dwo1327-gb-b
      
      
     
