# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install-dotnet    
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
     
    - name: InstallDatabase
      uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: 'mariadb'
        mysql-version: '10.6'
        root-password: 'root'
        user: 'user'
        password: 'password'
    - run: mysql -uroot -proot -h127.0.0.1 -e 'SELECT version()'

   
    - name: build
      run: dotnet build
    
    - name: release
      run: dotnet publish -o ./release
      
    - name: test
      run: dotnet test
      
    - name: build container
      run: docker build . --file Dockerfile --tag dwo1327
      #working-directory: ./release
    
    - name: tag
      run: docker tag dwo1327 idi2019.azurecr.io/dwo1327-s5backend
    
    - name: run_docker
      run: docker run dwo1327 -p 5000:80 -e docker run -p 5000:80 -e Azure__SignalR__ConnectionString="<DataSource=127.0.0.1;Database=guestbook;UserId=root;Password=root;>"
     
